version: "3.3"
services:
  database:
    image: postgres
    container_name: database
    volumes:
      - postgres:/var/lib/postgresl
    environment:
      POSTGRES_PASSWORD: database_password
      POSTGRES_USER: database_user
      POSTGRES_DB: greetings
    ports:
      - '5432:5432'
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4567:4567"
    depends_on:
      - database
volumes:
  postgres:
